Update README.md with v1 announcement.
Ostorlab/oxo pull request #651
Opened 2024-04-25 13:14 UTC by mohsinenar

2024-04-25 13:24 UTC, elyousfi5 submitted a review, later dismissed

2024-04-25 14:22 UTC, 3asm reviewed
Not your best work @mohsinenar I am used to excellent'er work from you.

2024-04-25 14:22 UTC, 3asm commented on README.md
> +
Command lineks can be nicer update it.

2024-04-25 14:22 UTC, 3asm commented on README.md
> +
Example has a dedicated section, reference it and remove them from here.

2024-04-25 14:22 UTC, 3asm commented on README.md
> +
Remove the pitch section.

2024-04-26 14:58 UTC, 3asm requested changes

2024-04-26 14:58 UTC, 3asm commented on README.md
> +To run `oxo` in a container, you may use the publicly available image and run the following command:
You forgot to update the screenshots.

2024-04-29 11:22 UTC, 3asm approved these changes

2024-04-29 11:22 UTC, merged