run the async mq send message using a thread safe asyncio API. & add task cleanup.
Ostorlab/oxo pull request #658
Opened 2024-05-10 17:20 UTC by deadly-panda

2024-05-10 17:25 UTC, mohsinenar commented on src/ostorlab/agent/agent.py
> +                for task in [t for t in tasks if not (t.done() or t.cancelled())]:
```suggestion
                for task in [t for t in tasks if (t.done() or t.cancelled()) is False]:
```

2024-05-10 17:49 UTC, rabsondev approved these changes

2024-05-10 18:12 UTC, 3asm requested changes

2024-05-10 18:12 UTC, 3asm commented on src/ostorlab/agent/agent.py
> +        task.cancel()
```suggestion
def _cancel_tasks() -> None:
    """Cancel all tasks when receiving a SIGINT (Interrupt from keyboard) or a SIGTERM (termination)."""
    for task in asyncio.all_tasks():
        task.cancel()
```

2024-05-10 18:12 UTC, 3asm commented on src/ostorlab/agent/agent.py
> +                    self._loop.add_signal_handler(sig, _at_exit_loop)
```suggestion
                self._loop.add_signal_handler(signal.SIGTERM, _at_exit_loop)
                self._loop.add_signal_handler(signal.SIGINT, _at_exit_loop)
```

2024-05-10 18:12 UTC, 3asm commented on src/ostorlab/agent/agent.py
> +                    self._loop.run_until_complete(task)
List comprehension if a for loop. At this point just use an if.

2024-05-13 10:42 UTC, 3asm requested changes

2024-05-13 11:59 UTC, 3asm approved these changes

2024-05-13 12:00 UTC, merged