Run scan endpoint OXO spec
Ostorlab/oxo pull request #665
Opened 2024-05-24 15:38 UTC by elyousfi5

2024-05-24 17:15 UTC, benyissa commented on src/ostorlab/serve_app/oxo.py
> +                pass
```suggestion
```

2024-05-27 14:39 UTC, 3asm requested changes

2024-05-27 14:39 UTC, 3asm commented on src/ostorlab/runtimes/local/runtime.py
> +            console.error(message)
Why!!!

2024-05-27 14:39 UTC, 3asm commented on src/ostorlab/runtimes/local/runtime.py
> +            return message
API returning a message to detente status is a BAAADD practice.

2024-06-03 08:46 UTC, 3asm commented
Ping @elyousfi5 what is the status of this PR?

2024-06-03 16:38 UTC, elyousfi5 commented
> Ping @elyousfi5 what is the status of this PR?

Depends on #679

2024-06-04 10:11 UTC, 3asm commented
Ping on PR @elyousfi5

2024-06-04 15:11 UTC, oussamaessaji commented on src/ostorlab/cli/scan/run/run.py
> +                logger.error(f"Error running scan: {e}")
```suggestion
                logger.error("Error running scan: %s", e)
```

2024-06-04 16:47 UTC, 3asm requested changes

2024-06-04 16:47 UTC, 3asm commented on src/ostorlab/cli/scan/run/run.py
> +                logger.error("Error running scan: %s", e)
Why wrap it, we want ti to fail and trigger a graphql error?

2024-06-04 16:47 UTC, 3asm commented on src/ostorlab/serve_app/oxo.py
> +        with models.Database() as session:
Should be split into separate methods.

2024-06-04 17:35 UTC, oussamaessaji commented on src/ostorlab/serve_app/oxo.py
> +                            .all()
put it in a var

2024-06-06 15:06 UTC, benyissa submitted a review, later dismissed
Instead of catching OstorlabError at each type of asset, Why not do it inside the runtime classes as we did for other exceptions?

2024-06-06 16:04 UTC, mohsinenar commented on src/ostorlab/runtimes/local/models/models.py
> +                progress=progress,
Progress is enum right?

2024-06-06 17:06 UTC, 3asm approved these changes

2024-06-06 17:16 UTC, elyousfi5 commented on src/ostorlab/runtimes/local/models/models.py
> +                progress=progress,
progress is enum
![image](https://github.com/Ostorlab/oxo/assets/144013278/373221a2-e644-4dc2-a86a-14668bb8d88e)

2024-06-07 07:52 UTC, 3asm approved these changes

2024-06-07 07:53 UTC, 3asm commented
Please resolve conflict and it is good to go.

2024-06-07 07:59 UTC, ErebusZ approved these changes

2024-06-07 08:54 UTC, 3asm approved these changes

2024-06-07 08:54 UTC, merged