Add assets models.
Ostorlab/oxo pull request #679
Opened 2024-05-30 14:00 UTC by deadly-panda

2024-05-30 16:29 UTC, 3asm approved these changes

2024-05-30 16:29 UTC, 3asm commented on src/ostorlab/runtimes/local/models/models.py
> +    }
Nice work.

2024-05-30 16:44 UTC, mohsinenar approved these changes

2024-05-30 17:00 UTC, PiranhaSa approved these changes
lgtm

2024-05-30 17:39 UTC, oussamaessaji commented on src/ostorlab/runtimes/local/models/models.py
> +    links = sqlalchemy.Column(sqlalchemy.String(1024))
why not array https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.ARRAY

2024-05-31 09:09 UTC, benyissa commented on src/ostorlab/runtimes/local/models/models.py
> +            bundle_id: The application identifier.
```suggestion
            package_name: The application identifier.
```

2024-05-31 09:50 UTC, benyissa requested changes
```python
class Network(Asset):
    __tablename__ = "network"
    id = sqlalchemy.Column(
        sqlalchemy.Integer, sqlalchemy.ForeignKey("asset.id"), primary_key=True
    )
    cidr = sqlalchemy.Column(sqlalchemy.String(50))
    __mapper_args__ = {
        "polymorphic_identity": "network",
    }
    
    ...
    
        @staticmethod
    def create(cidr: str):
       ....
        with Database() as session:
            network = Network(
                cidr=cidr,
            )
            session.add(network)
            session.commit()
            return network
```

### Benefit:
**Storage Efficiency**: Using CIDR notation (`cidr` field) means storing one entry per network, regardless of the number of IPs. Avoiding the storage of large lists of IPs, especially for large networks.

2024-05-31 10:46 UTC, elyousfi5 requested changes

2024-05-31 11:18 UTC, elyousfi5 commented on src/ostorlab/runtimes/local/models/models.py
> +    links = sqlalchemy.Column(sqlalchemy.String(1024))
why string ? i know ARRAY is not supported in sqlite but you can use json i think its better

2024-05-31 11:18 UTC, elyousfi5 commented on src/ostorlab/runtimes/local/models/models.py
> +    ips = sqlalchemy.Column(sqlalchemy.String(1024))
same !

2024-05-31 11:33 UTC, elyousfi5 commented on tests/runtimes/local/models/models_test.py
> +    models.Url.create(links=["https://example.com", "https://example42.com"])
i think we need method here.

![image](https://github.com/Ostorlab/oxo/assets/144013278/c113928d-63d7-4a9f-b8ef-f667623bb4b1)

or they will be considered as domain names ?

2024-06-03 09:23 UTC, deadly-panda commented on tests/serve_app/oxo_test.py
> +        assert response.status_code == 200, response.get_json()
I'm not sure I understand, for this case it's json, sinon we use `response.text` ?

2024-06-03 10:02 UTC, 3asm commented
Ping @deadly-panda on PR status.

2024-06-03 15:03 UTC, benyissa commented on src/ostorlab/runtimes/local/models/models.py
> +    def create(package_name: str = "", path: str = ""):
missing return type.

2024-06-03 17:30 UTC, 3asm approved these changes

2024-06-03 17:30 UTC, merged