Add reference model
Ostorlab/oxo pull request #680
Opened 2024-05-30 18:10 UTC by elyousfi5

2024-05-30 18:26 UTC, oussamaessaji commented on src/ostorlab/serve_app/types.py
> +            info (graphql_base.ResolveInfo): GraphQL resolve info.
no need for types

2024-05-31 08:57 UTC, benyissa commented on src/ostorlab/serve_app/types.py
> +            List[OxoReferenceType]: List of references.
```suggestion
            List of references.
```

2024-05-31 09:44 UTC, amine3 requested changes

2024-05-31 09:44 UTC, amine3 commented on src/ostorlab/runtimes/local/models/models.py
> +    url = sqlalchemy.Column(sqlalchemy.String(255))
Is 255 enough for the url?

2024-05-31 09:47 UTC, elyousfi5 commented on src/ostorlab/runtimes/local/models/models.py
> +    url = sqlalchemy.Column(sqlalchemy.String(255))
@amine3 i updated to 4096

2024-05-31 09:59 UTC, amine3 approved these changes

2024-05-31 10:09 UTC, merged