Ensure Oxo serve & RE_Oxo schemas are similar.
Ostorlab/oxo pull request #692
Opened 2024-06-05 12:46 UTC by deadly-panda

2024-06-05 12:49 UTC, deadly-panda commented on tests/serve_app/oxo_test.py
> +            headers={"X-Api-Key": f"{os.environ.get('RE_OXO_API_KEY', "")}"},
```suggestion
            headers={"X-Api-Key": f"{os.environ.get('RE_OXO_API_KEY', '')}"},
```

2024-06-10 15:04 UTC, 3asm requested changes

2024-06-10 15:04 UTC, 3asm commented on tests/serve_app/oxo_test.py
> +    re_oxo_enums = {}
Please group lines to have:

setup

run

assert.

2024-06-10 15:04 UTC, 3asm commented on tests/serve_app/oxo_test.py
> +    introspect_enums_query = """
CONST?

2024-06-10 15:04 UTC, 3asm commented on tests/serve_app/oxo_test.py
> +    for query_name, queriy_fields in re_oxo_queries.items():
Can you please add assert that the list is not empty.

2024-06-10 16:47 UTC, benyissa reviewed
Do we need to always run this check? Why not put it in a separate workflow and trigger it manually when needed? 

2024-06-11 12:43 UTC, 3asm commented
Ping @deadly-panda on PR fixed.

2024-06-12 16:03 UTC, 3asm approved these changes

2024-06-12 16:04 UTC, merged