Print complete oxo endpoint link.
Ostorlab/oxo pull request #700
Opened 2024-06-07 15:27 UTC by ErebusZ

2024-06-07 15:37 UTC, benyissa requested changes
I think we need to use console.info instead of print. since it has its own config.
![image](https://github.com/Ostorlab/oxo/assets/144700714/7347492c-1a37-4ea8-ae4c-e125f84f9cb3)

2024-06-07 15:50 UTC, 3asm requested changes

2024-06-07 15:50 UTC, 3asm commented on setup.cfg
> +    colorama
colorama!!!

2024-06-07 15:50 UTC, 3asm commented on src/ostorlab/cli/serve/serve.py
> +    )
Man, we use console for this!

2024-06-07 15:50 UTC, 3asm requested changes

2024-06-07 15:50 UTC, 3asm commented on src/ostorlab/cli/serve/serve.py
> +    print(
/graphql

2024-06-07 15:59 UTC, elyousfi5 commented
> I think we need to use console.info instead of print. since it has its own config. ![image](https://private-user-images.githubusercontent.com/144700714/337712505-7347492c-1a37-4ea8-ae4c-e125f84f9cb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzYyNjYsIm5iZiI6MTcxNzc3NTk2NiwicGF0aCI6Ii8xNDQ3MDA3MTQvMzM3NzEyNTA1LTczNDc0OTJjLTFhMzctNGVhOC1hZTRjLWUxMjVmODRmOWNiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxNTU5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjcyMzgxNmVjZGRkZWI4ZjJlODQ1ZmZjNWQzMzY2NWQ1ZGQ5MDA1NGVjYjI5MjQ5ODYxYjJiMWRhYjQ1Zjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OYVZ4dad_1TT8DmANK3NoaSO5nYOmWZO3XPmtkIX0Qs)
> 
> console.success(f"Serving on : http://{host}:{port}/oxo\n") ![image](https://private-user-images.githubusercontent.com/144700714/337713391-583b9bdb-80e4-48e0-a752-dfa0361d57cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzYyNjYsIm5iZiI6MTcxNzc3NTk2NiwicGF0aCI6Ii8xNDQ3MDA3MTQvMzM3NzEzMzkxLTU4M2I5YmRiLTgwZTQtNDhlMC1hNzUyLWRmYTAzNjFkNTdjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxNTU5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGEyNjE0NjE5MTI1OTY5ZGM3ZDEyYjg3ODJlYTMzNjFmYjFkNWFjMzBmYTEzZGJiN2Q5NWI1YjBmNjgwZDBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kTkUVf1psvDXmP3VbSECPNRiY9muJjVV6c2WsmO6-Lc)

+1

2024-06-07 16:55 UTC, oussamaessaji commented on src/ostorlab/cli/serve/serve.py
> +    console.success(f"Serving on : http://{host}:{port}/graphql")
Can you add the second host

2024-06-07 17:01 UTC, 3asm submitted a review, later dismissed

2024-06-07 17:01 UTC, 3asm commented on src/ostorlab/cli/serve/serve.py
> +    console.success(f"Serving on : http://{host}:{port}/graphql")
```suggestion
    console.success(f"Serving API on : http://{host}:{port}/graphql")
```

2024-06-09 09:51 UTC, 3asm approved these changes

2024-06-09 09:52 UTC, merged