Workflow to generate and build Ui.
Ostorlab/oxo pull request #712
Opened 2024-06-12 15:47 UTC by mohsinenar

- **First draft**
- **First working draft**
- **First working draft**
- **Unit tests**
- **replace custom_risk_rating by risk_rating**
- **Trigger the workflow**
- **Use exceptions instead of message_status**
- **refactor**
- **Fix unit tests**
- **Fix unit tests**
- **Fix unit tests**
- **Update src/ostorlab/serve_app/oxo.py**
- **Draft**
- **Resolve agents**
- **Refactor**
- **Draft**
- **Delete agent group mutation**
- **Fix comments**
- **Trigger github worklow.**
- **Add paginator.**
- **Fix unit tests #1**
- **Fix Ruff**
- **Add paginator.**
- **Fix tests.**
- **Appy ruff.**
- **Fix check for count method.**
- **query agent group definitions**
- **Docstrings**
- **Add page info**
- **Stop scan OXO API**
- **Stop scan OXO API**
- **Add more tests.**
- **Add Authorization to the oxo server**
- **Draft mutation**
- **use Optional instead of |**
- **Update src/ostorlab/serve_app/types.py**
- **Add support for ubjson**
- **Update tests/serve_app/common_test.py**
- **Update**
- **Ruff.**
- **Update to main.**
- **Update to main.**
- **Update to main.**
- **Solve conflict**
- **add_authorization_to_oxo_server_endpoint : refactor!**
- **add_authorization_to_oxo_server_endpoint : refactor after merge!**
- **Add support for ubjson response**
- **Update conftest.py**
- **Update oxo_test.py**
- **Fix unit test**
- **use authenticated_flask_client instead of client**
- **Minor fixes.**
- **Add assets models.**
- **oxo serve --refresh-api-key**
- **oxo serve --refresh-api-key**
- **apply ruff & fix docstring typose.**
- **Fix comments**
- **Update**
- **Add reference model**
- **Fix unit tests**
- **Add testflight missing import.**
- **Add testflight missing import.**
- **Add testflight missing import.**
- **Fix comment**
- **Update**
- **Add testflight missing import.**
- **Add testflight missing import.**
- **Add pagination to vulnerabilities query**
- **Update setup.cfg**
- **Update**
- **Add cors to flask app.**
- **Change url length from 255 to 4096**
- **Update src/ostorlab/serve_app/types.py**
- **Update**
- **Update**
- **Create asset API.**
- **Drafting asset part**
- **Use agent_key instead of key**
- **working draft + Unit tests**
- **Fix comments about typing**
- **try-catch to fix flaky unit test**
- **Address comments.**
- **try-catch to fix flaky unit test**
- **draft**
- **fix unit test**
- **Address comments.**
- **fix resolve references and add kv vulnz pagination**
- **correct annotation**
- **Apply ruff formatiing.**
- **fix resolve references**
- **fix resolve references**
- **Fix workflows getting cancelled.**
- **Fix windows workflow.**
- **Delete used macOS installer workflow config.**
- **Set check_same_thread to false.**
- **Fix stop scan unit test failing on windows.**
- **Address comments.**
- **Remove pytest.mark.stop**
- **Fix missing OPTIONS support.**
- **Fix failing tests on windows & fix broken mani merge.**
- **Fix conflict**
- **Multiple fixes**
- **Fix wrong paths on windows.**
- **Remove unused fixture**
- **Mock unit tests**
- **Resolve conflict**
- **Fix unit tests**
- **Adapt oxo assets types to the new name.**
- **Update src/ostorlab/cli/scan/run/run.py**
- **Raise and catch**
- **Split logic into methods**
- **Use progress instead of progress.name**
- **Update KB**
- **Fix scan-asset relationship**
- **Update version**
- **Adapt query asset to RE**
- **Fix comments**
- **Add test for scan info when resolving asset**
- **link scan to asset and ag (draft)**
- **Add return types**
- **Fix linter**
- **Link asset and ag to cli scan**
- **Refactor**
- **Refactor**
- **Fix unit test attempt 1**
- **Fix comments**
- **Revert "Link asset and agent group to cli scan"**
- **Print complete oxo endpoint link.**
- **fix endpoint name**
- **use console**
- **remove colorama**
- **Update src/ostorlab/cli/serve/serve.py**
- **Link cli scan with asset and agent group.**
- **minor fixes**
- **clean up unit tests 1**
- **Add condition for local runtime**
- **Add condition for local runtime**
- **Clean up unit tests**
- **Clean up unit tests**
- **Fix comments**
- **Fix comment**
- **Fix unit test**
- **Update src/ostorlab/runtimes/local/runtime.py**
- **Fix comments**
- **Adapt create assets mutations to YAML format in oxo_api**
- **minor change**
- **Adapt networks to RE**
- **Add asset types to AgentGroup model.**
- **Fix ruff**
- **Add static files.**
- **Add command to serve UI.**
- **Add command to serve UI.**
- **Apply ruff.**
- **Revert "Add asset types to AgentGroup model."**
- **Revert "Adapt create assets mutations to YAML format in oxo_api"**
- **Use just number**
- **Fix unit test**
- **Remove static files.**
- **Cancel change in setup.cfg**
- **Workflow to generate and build Ui.**

2024-06-12 16:00 UTC, rabsondev commented on .github/workflows/python-publish.yml
> +#          push: true
Needed?

2024-06-14 05:53 UTC, 3asm requested changes

2024-06-14 05:53 UTC, 3asm commented on .github/workflows/python-publish.yml
> +      run: cp -r src/oxotitan/.output/public src/ostorlab/ui/static_files
/static

2024-06-14 05:53 UTC, 3asm commented on .github/workflows/release_linux_mac_bin.yaml
> +      run: cp -r src/oxotitan/.output/public src/ostorlab/ui/static_files
/static

2024-06-14 11:14 UTC, 3asm commented
Please fix workflow.

2024-06-14 16:00 UTC, 3asm approved these changes

2024-06-14 16:00 UTC, merged