Account for no asset
Ostorlab/oxo pull request #768
Opened 2024-08-06 13:40 UTC by ErebusZ

2024-08-06 13:48 UTC, mohsinenar commented on src/ostorlab/cli/scan/run/run.py
> +                        asset_group.targets if asset_group is not None else None,
Use Kwargs

2024-08-07 09:05 UTC, 3asm requested changes

2024-08-07 09:05 UTC, 3asm commented on src/ostorlab/cli/scan/run/run.py
> +                        asset_group.targets if asset_group is not None else None,
Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test, Unit test.

2024-08-07 18:14 UTC, 3asm approved these changes

2024-08-08 07:58 UTC, merged