Add extra_headers to v3.asset.file.api_schema.graphql proto
Ostorlab/oxo pull request #813
Opened 2024-09-30 16:42 UTC by elyousfi5

2024-09-30 18:04 UTC, 3asm requested changes

2024-09-30 18:04 UTC, 3asm commented on src/ostorlab/agent/message/proto/v3/asset/file/api_schema/graphql/graphql.proto
> +message Header {
Should you add this to each `api_schema`. Not just GraphQL.

2024-09-30 18:08 UTC, benyissa commented on setup.cfg
> +    pytest-httpx==0.30.0
Can you explain why we're pinning this version, in case we need to check later if an upgrade is possible?

2024-10-01 09:57 UTC, 3asm approved these changes

2024-10-01 09:57 UTC, merged