Add proto for kill scan message
Ostorlab/oxo pull request #814
Opened 2024-09-30 18:10 UTC by oussamaessaji

This PR implements the proto for kill message, this message will be used to kill all the agents within a universe.

2024-09-30 18:44 UTC, 3asm requested changes

2024-09-30 18:44 UTC, 3asm commented on src/ostorlab/agent/message/proto/v3/report/event/scan/kill/kill.proto
The selector should `v3.kill`.
Inside should be a string reason.

2024-10-01 10:04 UTC, benyissa commented on src/ostorlab/agent/message/proto/v3/report/event/scan/kill/kill.proto
@3asm shouldn't we keep the same structure as scan.done ?

2024-10-01 10:50 UTC, 3asm approved these changes

2024-10-01 10:54 UTC, merged