Add support CI_SCAN for a link.
Ostorlab/oxo pull request #837
Opened 2024-11-14 02:24 UTC by amine3

This PR adds support in the CLI of the CI_SCAN for the asset type link.

Command example: `ostorlab --api-key APIKEY ci-scan run --title test1 --api-schema /tmp/schema.txt --scan-profile=full_web_scan link --url https://google.com`

Output:

![image](https://github.com/user-attachments/assets/33bf9ea8-1a2f-4ab0-a3ad-56e3c9f0f894)

2024-11-14 08:48 UTC, rabsondev commented on src/ostorlab/apis/scan_create.py
> +        api_schema: io.FileIO = None,
```suggestion
        sboms: Optional[list[io.FileIO]] = None,
        api_schema: Optional[io.FileIO] = None,
```

2024-11-14 08:48 UTC, rabsondev commented on src/ostorlab/apis/scan_create.py
> +        filtered_url_regexes: [List[str]] = None,
```suggestion
        filtered_url_regexes: Optional[[List[str]]] = None,
```

2024-11-14 08:49 UTC, rabsondev commented on src/ostorlab/cli/ci_scan/run/assets/link.py
> +    if test_credentials_name:
Explicit check.

2024-11-14 08:53 UTC, rabsondev requested changes

2024-11-14 08:53 UTC, rabsondev commented on src/ostorlab/cli/ci_scan/run/assets/link.py
> +    if ctx.obj.get("api_key"):
```suggestion
    if ctx.obj.get("api_key") is not None:
```

2024-11-14 08:53 UTC, rabsondev commented on src/ostorlab/cli/ci_scan/run/assets/link.py
> +            if test_credentials:
Explicit check.

2024-11-14 08:53 UTC, rabsondev commented on src/ostorlab/cli/ci_scan/run/assets/link.py
> +                qps,
Please use `kwargs`.

2024-11-14 08:53 UTC, rabsondev commented on src/ostorlab/cli/ci_scan/run/assets/link.py
> +def _create_test_credentials(test_credentials, runner):
Missing type hints for params and return type.

2024-11-14 08:53 UTC, rabsondev commented on src/ostorlab/cli/ci_scan/run/assets/link.py
> +    scan_id = scan_result.get("data").get("createWebScan").get("scan").get("id")
What if one of the `.get` returns `None`.

2024-11-14 09:31 UTC, 3asm approved these changes

2024-11-14 09:31 UTC, 3asm commented on src/ostorlab/apis/scan_create.py
> +    "full_web_scan": "Full Web Scan",
Shouldn't we change the other to mobile scan?

2024-11-14 09:31 UTC, 3asm commented on src/ostorlab/cli/ci_scan/run/run.py
> +)
I don't see SBOM?

2024-11-14 09:47 UTC, amine3 commented on src/ostorlab/cli/ci_scan/run/run.py
> +)
It is already there line 93.

2024-11-14 10:19 UTC, merged

2024-11-28 09:38 UTC, oussamaessaji commented
Preparing review...